### ISSUE TITLE
WCF implementation

### ISSUE THREAD

**Issue by divyesh1432** [hogaf/Castle.Facilities.Aspect#2]
Can you please show or provide an example how this works in WCF with WcfFacility?
I tried to implement it but my WCF is failing to invoke interceptor method.

Below is the code I have configured in Global.asax

```
        private WindsorContainer container;

        protected void Application_Start(object sender, EventArgs e)
        {
            container = new WindsorContainer();

            container.AddFacility<WcfFacility>();

            container.Register(
                Component.For<IInterceptor>().ImplementedBy<LogAdvice>().Named("myinterceptor"),
                Component.For<IDataMigration>().ImplementedBy<DataMigration>().Named("MigrationWeb.DataMigration")

                );
        }
```

Thanks

**Comment by hogaf** [comment]
Actually, there is nothing interfering with the WcfFacility. As you might have seen in the sample project **(Castle.Facilities.Aspect.SampleApp)** you should call for the **AspectFacility** first which literally registers the IPointcut interface, Then you can intercept the whole class using an **InheritancePointcut** or decorate a method in your DataMigration class with something might you name **LogAttribute** uisng **AttributePointcut**.

For the first approach in order to intercept the whole class you can use:
```
container.AddFacility<AspectFacility>(x =>
            {
               //Every type implementing the IDataMigration interface will be intercepted
                x.AddInheritancePointcut<IDataMigration, InhertiedLogAdvice>();
            });
```
Or for the second approach you can create an special attribute like this :
```
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class LogAttribute : Attribute
    {
    }
```
and Decorate a method in your DataMigration class and use the facility like this:
```
container.AddFacility<AspectFacility>(x =>
            {
                //Every method decorated with the LogAttribute will be intercepted
                x.AddAttributePointcut<LogAttribute, LogAdvice>();
            });
```
